_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.7
        t:
            "1":
                - 5
                - 53
                - 55
                - 87
            "2":
                - 5
                - 53
                - 55
                - 87
            "3":
                - 23
                - 55
            "4": 3.9.7
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-x86_64
